name: Build and Run Dockerized App

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Check Docker version
        run: docker --version

      - name: Set up Java & Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build project using Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t security-demo-app .

      - name: Run Docker container
        run: docker run -d -p 8081:8080 --name security-demo-container security-demo-app

      - name: List running containers
        run: docker ps
